name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check code out
        uses: actions/checkout@v3

      - name: Intall Pnpm
        uses: pnpm/action-setup@v2

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Check linter violations
        run: pnpm lint

      - name: Check code format
        run: pnpm format --check

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v3

      - name: Intall Pnpm
        uses: pnpm/action-setup@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build UI
        run: pnpm --filter ui build

      - name: Run tests
        run: pnpm test

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: packages/svelte/coverage/clover.xml,packages/toolshot/coverage/clover.xml,packages/ui/coverage/clover.xml,packages/vite-plugin-atelier/coverage/clover.xml
